//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jednoslad2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jednosladEntities : DbContext
    {
        public jednosladEntities()
            : base("name=jednosladEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

		public virtual DbSet<klienci> kliencis { get; set; }
        public virtual DbSet<motocykle> motocykles { get; set; }
        public virtual DbSet<transakcje> transakcjes { get; set; }
    }
}
