//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jednoslad2
{
    using System;
    using System.Collections.Generic;
    
    public partial class motocykle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public motocykle()
        {
            this.transakcjes = new HashSet<transakcje>();
        }
    
        public int id { get; set; }
        public string marka { get; set; }
        public Nullable<System.DateTime> rok_produkcji { get; set; }
        public Nullable<decimal> pojemnosc { get; set; }
        public Nullable<decimal> cena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transakcje> transakcjes { get; set; }
    }
}
